# Generated by Django 5.0.4 on 2024-04-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(default='Sedan', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.FloatField(default=2.2),
            preserve_default=False,
        ),
    ]
